[server]
dot_port = 853
doh_port = 443
tls_cert = "/etc/letsencrypt/dns.sawyer.services.crt"
tls_key = "/etc/letsencrypt/dns.sawyer.services.key"
default_ttl = 300

[blocking]
mode = "nxdomain"

[blocklists]
refresh_interval_secs = 43200
urls = [
  "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
  "https://easylist.to/easylist/easylist.txt",
  "https://easylist.to/easylist/easyprivacy.txt",
  "https://secure.fanboy.co.nz/fanboy-annoyance.txt",
  "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt",
  "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/pro.plus.txt",

  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/ads.txt",
  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/phishing.txt",
  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/smart-tv.txt",
  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/tracking.txt",
  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/fraud.txt",
  "https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/main/ransomware.txt",
]

[upstream]
strategy = "sequential"
urls = [
  "https://cloudflare-dns.com/dns-query",
  "https://dns.quad9.net/dns-query",
  "https://anycast.uncensoreddns.org/dns-query",
  "tls://1.1.1.1:853#cloudflare-dns.com",
]

[static_hosts]
"homenas" = "100.75.47.18"
"bevbot" = "100.116.101.69"
"bevbot2" = "100.116.124.26"

[cache]
enabled = true
max_entries = 10000
