# My homelab ai file
version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  fooocus_data:
    driver: local
  ollama_data:
    driver: local
  ollama-ui_data:
    driver: local

services:
  fooocus:
    image: ashleykza/fooocus
    container_name: fooocus
    restart: always
    networks:
      - web
    expose:
      - 3001
    env_file:
      - ./secrets/homelab.env
    volumes:
      - fooocus_data:/workspace
    environment:
      - VENV_PATH=/workspace/venvs/fooocus
    labels:
      # define regex middleware
      - "traefik.http.middlewares.fooocus-redirectregex.redirectregex.regex=^/*.*/log.html"
      - "traefik.http.middlewares.fooocus-redirectregex.redirectregex.replacement=/"

      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.fooocus.entrypoints=http"
      - "traefik.http.routers.fooocus.rule=Host(`fooocus.${DOMAIN}`)"
      - "traefik.http.middlewares.fooocus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.fooocus.middlewares=fooocus-https-redirect"
      - "traefik.http.routers.fooocus-secure.entrypoints=https"
      - "traefik.http.routers.fooocus-secure.rule=Host(`fooocus.${DOMAIN}`)"
      - "traefik.http.routers.fooocus-secure.tls=true"
      - "traefik.http.routers.fooocus-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.fooocus-secure.middlewares=forward-auth"
      - "traefik.http.routers.fooocus-secure.middlewares=fooocus-redirectregex"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    networks:
      - internal
    expose:
      - 11434
    env_file:
      - ./secrets/homelab.env
    volumes:
      - ollama_data:/root/.ollama
    labels:
      - "traefik.enable=false"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ollama-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-ui
    restart: always
    depends_on:
      - ollama
    networks:
      - web
      - internal
    expose:
      - 8080
    env_file:
      - ./secrets/homelab.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ollama-ui_data:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.ollama-ui.entrypoints=http"
      - "traefik.http.routers.ollama-ui.rule=Host(`ollama.${DOMAIN}`)"
      - "traefik.http.middlewares.ollama-ui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.ollama-ui.middlewares=ollama-ui-https-redirect"
      - "traefik.http.routers.ollama-ui-secure.entrypoints=https"
      - "traefik.http.routers.ollama-ui-secure.rule=Host(`ollama.${DOMAIN}`)"
      - "traefik.http.routers.ollama-ui-secure.tls=true"
      - "traefik.http.routers.ollama-ui-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.ollama-ui-secure.middlewares=forward-auth"
