---
- name: Configure homelab gateway server (Debain)
  hosts: "*"
  remote_user: root
  
  pre_tasks: 
    - name: update 
      ansible.builtin.include_tasks:
        file: tasks/apt.yml

    - name: Install packages
      apt:
        pkg:
          - docker.io

    - name: Crate docker stack dir
      ansible.builtin.file:
        path: ~/compose-files/
        state: directory

    - name: Copy secrets file
      ansible.builtin.copy:
        decrypt: true
        src: secrets.env
        dest: ~/compose-files

  tasks:
    # allows ansible to easily connect back for updates
    - name: install and configure tailscale
      ansible.builtin.include_tasks:
        file: tasks/tailscale.yml
      vars:
        tailscale_hostname: gateway

    - name: Copy rathole config
      ansible.builtin.copy:
        decrypt: true
        src: docker/rathole/rathole.toml
        dest: ~/

    - name: Start Rathole container
      docker_container:
        name: "rathole"
        recreate: yes
        image: rapiz1/rathole
        volumes: 
          - /root/rathole.toml:/app/config.toml
        command: --server /app/config.toml
