---
- name: Configure homelab gateway server (Debain)
  hosts: "*"
  remote_user: root
  
  pre_tasks: 
    - name: Copy secrets file
      ansible.builtin.copy:
        decrypt: true
        src: secrets.env
        dest: /root/files

    - name: Copy nginx config
      ansible.builtin.copy:
        src: docker/nginx/nginx.conf
        dest: /root/sender.conf

    - name: Copy crowdsec bouncer config
      ansible.builtin.copy:
        src: files/crowdsec-firewall-bouncer.yaml
        dest: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml

    - name: Get crowdsec api key
      ansible.builtin.shell:
        cat /root/files/secrets.env | grep CROWDSEC_API_KEY | sed 's/^.*CROWDSEC_API_KEY=//'
      register: crowdsec_token
      ignore_errors: true
      changed_when: false

    - name: Replace crowdsec api with secret
      ansible.builtin.replace:
        path: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
        regexp: '"${API_KEY}"'
        replace: '"{{ crowdsec_token.stdout }}"'

  tasks:
    - name: add crowdsec repo
      ansible.builtin.shell: curl -s https://install.crowdsec.net | sudo sh
    
    - name: Install packages
      apt:
        pkg:
          - docker.io
          - crowdsec-firewall-bouncer-iptables

    - name: Start Nginx container
      docker_container:
        name: "nginx"
        recreate: yes
        image: nginx
        network_mode: "host"
        user: root
        volumes: 
          - /root/sender.conf:/etc/nginx/nginx.conf
