# My homelab media file
version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    restart: always
    networks:
      - web
    ports:
      - 8096:8096/tcp
      - 8920:8920
    volumes:
      - ${DRIVE}/shows/:/data/tvshows/
      - ${DRIVE}/movies/:/data/movies/
      - ${DRIVE}/certbot/certificates/:/data/certs/
      - ${DRIVE}/jellyfin-conf/:/config/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=${DNS}"
      - "traefik.http.services.jellyfin-secure.loadbalancer.server.port=8096"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    networks:
      - web
    volumes:
      - ${DRIVE}/:/data
    env_file:
      - ./secrets/homelab.env
    environment:
      - OPENVPN_OPTS=--pull-filter ignore ifconfig-ipv6
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      # any ports needed to expose services through traefik need to be defined here
      - 9091:9091 # transmission
      - 3333:3333 # bitmagnet
      # BitTorrent ports:
      - 3334:3334/tcp
      - 3334:3334/udp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # transmission
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN}`) || Host(`torrent.${DOMAIN}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.transmission-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.transmission.middlewares=transmission-https-redirect"
      - "traefik.http.routers.transmission-secure.entrypoints=https"
      - "traefik.http.routers.transmission-secure.rule=Host(`transmission.${DOMAIN}`) || Host(`torrent.${DOMAIN}`)"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.tls.certresolver=${DNS}"
      - "traefik.http.services.transmission-secure.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission-secure.middlewares=forward-auth"

  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    restart: always
    container_name: bitmagnet
    network_mode: "service:transmission-openvpn"
    # webui on port 3333
    env_file:
      - ./secrets/homelab.env
    environment:
      # uses this name because ports are exposed through transmission
      - POSTGRES_HOST=localhost
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.bitmagnet.entrypoints=http"
      - "traefik.http.routers.bitmagnet.rule=Host(`bitmagnet.${DOMAIN}`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.bitmagnet-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bitmagnet.middlewares=bitmagnet-https-redirect"
      - "traefik.http.routers.bitmagnet-secure.entrypoints=https"
      - "traefik.http.routers.bitmagnet-secure.rule=Host(`bitmagnet.${DOMAIN}`)"
      - "traefik.http.routers.bitmagnet-secure.tls=true"
      - "traefik.http.routers.bitmagnet-secure.tls.certresolver=${DNS}"
      - "traefik.http.services.bitmagnet-secure.loadbalancer.server.port=3333"
      - "traefik.http.routers.bitmagnet-secure.middlewares=forward-auth"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    network_mode: "service:transmission-openvpn"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./secrets/homelab.env
    environment:
      - POSTGRES_DB=bitmagnet
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
    labels:
      - "traefik.enable=false"
