# My homelab utilities file
version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  portainer_data:
    driver: local
  languagetool_ngrams:
    driver: local
  languagetool_fasttext:
    driver: local

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    networks:
      - web
    expose:
      - 80
    volumes:
      - ./dashy/conf.yml:/app/public/conf.yml:ro
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dashy.entrypoints=http"
      - "traefik.http.routers.dashy.rule=Host(`dashy.${DOMAIN}`) || Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.dashy.middlewares=dashy-https-redirect"
      - "traefik.http.routers.dashy-secure.entrypoints=https"
      - "traefik.http.routers.dashy-secure.rule=Host(`dashy.${DOMAIN}`) || Host(`${DOMAIN}`)"
      - "traefik.http.routers.dashy-secure.tls=true"
      - "traefik.http.routers.dashy-secure.tls.certresolver=${DNS}"

  portainer:
    container_name: portainer
    image: portainer/portainer-ee
    restart: always
    command: --tlsskipverify
    networks:
      - web
    expose:
      - 9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.portainer-secure.middlewares=forward-auth"
      - "traefik.http.services.portainer-secure.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.remove-path.stripprefix.prefixes=/portainer"
      - "traefik.http.routers.portainer.middlewares=remove-path@docker"

  registry: # My own docker registry
    container_name: registry
    image: registry
    restart: always
    networks:
      - web
    expose:
      - 5000
    env_file:
      - ./secrets/homelab.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.registry.entrypoints=http"
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.middlewares.registry-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.registry.middlewares=registry-https-redirect"
      - "traefik.http.routers.registry-secure.entrypoints=https"
      - "traefik.http.routers.registry-secure.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.routers.registry-secure.tls=true"
      - "traefik.http.routers.registry-secure.tls.certresolver=${DNS}"

  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    networks:
      - web
    expose:
      - 8080
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - ./secrets/homelab.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.searxng.entrypoints=http"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${DOMAIN}`) || Host(`searx.${DOMAIN}`) || Host(`search.${DOMAIN}`)"
      - "traefik.http.middlewares.searxng-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.searxng.middlewares=searxng-https-redirect"
      - "traefik.http.routers.searxng-secure.entrypoints=https"
      - "traefik.http.routers.searxng-secure.rule=Host(`searxng.${DOMAIN}`) || Host(`searx.${DOMAIN}`) || Host(`search.${DOMAIN}`)"
      - "traefik.http.routers.searxng-secure.tls=true"
      - "traefik.http.routers.searxng-secure.tls.certresolver=${DNS}"

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: always
    command: "--noauth"
    networks:
      - web
    env_file:
      - ./secrets/homelab.env
    volumes:
      - ${DRIVE}/media/shows:/srv/shows
      - ${DRIVE}/media/movies:/srv/movies
      - ${DRIVE}/media/music:/srv/music
      - ${DRIVE}/media/complete:/srv/complete
      - ${DRIVE}/media/else:/srv/else
      - ${DRIVE}/incomplete:/srv/incomplete
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.files.entrypoints=http"
      - "traefik.http.routers.files.rule=Host(`files.${DOMAIN}`) || Host(`filebrowser.${DOMAIN}`)"
      - "traefik.http.middlewares.files-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.files.middlewares=files-https-redirect"
      - "traefik.http.routers.files-secure.entrypoints=https"
      - "traefik.http.routers.files-secure.rule=Host(`files.${DOMAIN}`) || Host(`filebrowser.${DOMAIN}`)"
      - "traefik.http.routers.files-secure.tls=true"
      - "traefik.http.routers.files-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.files-secure.middlewares=forward-auth"

  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    restart: always
    networks:
      - web
    expose:
      - 80
    env_file:
      - ./secrets/homelab.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.ping.entrypoints=http"
      - "traefik.http.routers.ping.rule=Host(`ping.${DOMAIN}`) || Host(`smokeping.${DOMAIN}`) "
      - "traefik.http.middlewares.ping-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.ping.middlewares=ping-https-redirect"
      - "traefik.http.routers.ping-secure.entrypoints=https"
      - "traefik.http.routers.ping-secure.rule=Host(`ping.${DOMAIN}`) || Host(`smokeping.${DOMAIN}`) "
      - "traefik.http.routers.ping-secure.tls=true"
      - "traefik.http.routers.ping-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.ping-secure.middlewares=forward-auth"

  languagetool:
    image: meyay/languagetool
    container_name: languagetool
    restart: always
    networks:
      - web
    env_file:
      - ./secrets/homelab.env
    cap_drop:
      - ALL
    cap_add:
      - CAP_SETUID
      - CAP_SETGID
      - CAP_CHOWN
    security_opt:
      - no-new-privileges
    ports:
      - 8010:8010
    environment:
      download_ngrams_for_langs: en
      langtool_languageModel: /ngrams
      langtool_fasttextModel: /fasttext/lid.176.bin
    volumes:
      - languagetool_ngrams:/ngrams
      - languagetool_fasttext:/fasttext
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.languagetool.entrypoints=http"
      - "traefik.http.routers.languagetool.rule=Host(`languagetool.${DOMAIN}`) || Host(`smokelanguagetool.${DOMAIN}`) "
      - "traefik.http.middlewares.languagetool-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.languagetool.middlewares=languagetool-https-redirect"
      - "traefik.http.routers.languagetool-secure.entrypoints=https"
      - "traefik.http.routers.languagetool-secure.rule=Host(`languagetool.${DOMAIN}`) || Host(`smokelanguagetool.${DOMAIN}`) "
      - "traefik.http.routers.languagetool-secure.tls=true"
      - "traefik.http.routers.languagetool-secure.tls.certresolver=${DNS}"
      - "traefik.http.routers.languagetool-secure.middlewares=forward-auth"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./secrets/homelab.env
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REVIVE_STOPPED: true
    command: --cleanup
    restart: always
    labels:
      - "traefik.enable=false"
