networks:
  dns:
    ipam:
      config:
        - subnet: 172.55.0.0/24

services:
  dns-rs:
    image: ghcr.io/legitcamper/dns-rs:latest
    container_name: dns-rs
    restart: always
    user: "1000:1000"
    ports:
      - "853:853/tcp"
      - "443:443/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/dns/dns-rs/config.toml:/etc/dns-rs/config.toml:ro
      - /root/letsencrypt/dns-rs-certs:/etc/letsencrypt:ro

  lego:
    image: goacme/lego:v5.2.2
    container_name: lego-certbot
    restart: always
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_KEY}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          /lego run \
            --accept-tos \
            --email "${CF_API_EMAIL}" \
            --dns cloudflare \
            --domains "dns.${DOMAIN}" \
            --path /etc/letsencrypt/ \
            --renew-days 30;
          mkdir -p /etc/letsencrypt/dns-rs-certs;
          cp /etc/letsencrypt/certificates/dns.${DOMAIN}.crt /etc/letsencrypt/dns-rs-certs/;
          cp /etc/letsencrypt/certificates/dns.${DOMAIN}.key /etc/letsencrypt/dns-rs-certs/;
          chown -R 1000:1000 /etc/letsencrypt/dns-rs-certs;
          sleep 12h;
        done
    volumes:
      - /root/letsencrypt:/etc/letsencrypt:rw
