---
- name: Get cifs host
  ansible.builtin.shell:
    cat /home/sawyer/compose-files/secrets.env | grep NETWORK_DRIVE_HOST | sed 's/^.*NETWORK_DRIVE_HOST=//'
  register: cifs_host 
  ignore_errors: true
  changed_when: false

- name: Get cifs username
  ansible.builtin.shell:
    cat /home/sawyer/compose-files/secrets.env | grep NETWORK_DRIVE_USERNAME | sed 's/^.*NETWORK_DRIVE_USERNAME=//'
  register: cifs_user
  ignore_errors: true
  changed_when: false

- name: Get cifs password
  ansible.builtin.shell:
    cat /home/sawyer/compose-files/secrets.env | grep NETWORK_DRIVE_PASSWORD | sed 's/^.*NETWORK_DRIVE_PASSWORD=//'
  register: cifs_password
  ignore_errors: true
  changed_when: false

- name: Verify /mnt/homelab is mounted
  ansible.builtin.command: findmnt -n /mnt/homelab
  register: media_findmnt
  changed_when: false
  failed_when: false

- name: Verify /mnt/media is mounted
  ansible.builtin.command: findmnt -n /mnt/media
  register: media_findmnt
  changed_when: false
  failed_when: false

- name: Ensure homelab mount is in fstab and mounted
  become: true
  ansible.posix.mount:
    path: /mnt/homelab
    src: "//{{ cifs_host.stdout }}/homelab"
    fstype: cifs
    opts: "username={{ cifs_user.stdout }},password={{ cifs_password.stdout }},vers=3.0,rw,nofail,_netdev,uid=1000,gid=1000,actimeo=1"
    state: mounted

- name: Ensure media mount is in fstab and mounted
  become: true
  ansible.posix.mount:
    path: /mnt/media
    src: "//{{ cifs_host.stdout }}/media"
    fstype: cifs
    opts: "username={{ cifs_user.stdout }},password={{ cifs_password.stdout }},vers=3.0,rw,nofail,_netdev,uid=1000,gid=1000,actimeo=30"
    state: mounted
   
- name: Verify /mnt/media is mounted
  ansible.builtin.command: findmnt -n /mnt/media
  changed_when: false

- name: Verify /mnt/homelab is mounted
  ansible.builtin.command: findmnt -n /mnt/homelab
  changed_when: false
