networks:
  web:
    external: true
  internal: # Not exposed via traefik (dbs & severices
    external: false
  # This network exists just so adugard can have a static ip for tcp routing
  dns:
    ipam:
      config:
        - subnet: 172.55.0.0/24

volumes:
  logs:
  uptimekuma:
  crowdsec-db:
  crowdsec-config:
  ollama-open-webui:
  jellyfin-config:
  jellyfin-cache:
  adguard-work:

services:
  komodo-core:
    image: ghcr.io/mbecker20/komodo:latest
    container_name: komodo-core
    restart: always
    user: "1000:1000"
    depends_on:
      - komodo-mongo
      - komodo-periphery
    networks:
      - internal
      - web
    expose:
      - 9120
    environment: 
      KOMODO_HOST: ${KOMODO_HOST}
      KOMODO_TITLE: Komodo 
      KOMODO_ENSURE_SERVER: http://komodo-periphery:8120 # Creates the "default" server.
      KOMODO_MONGO_ADDRESS: komodo-mongo:27017
      KOMODO_MONGO_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_MONGO_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_LOCAL_AUTH: false 
      KOMODO_PASSKEY: ${KOMODO_PASSKEY}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_GITHUB_OAUTH_ENABLED: true       
      KOMODO_GITHUB_OAUTH_ID: ${KOMODO_GITHUB_OAUTH_ID}
      KOMODO_GITHUB_OAUTH_SECRET: ${KOMODO_GITHUB_OAUTH_SECRET}

  komodo-periphery:
    image: ghcr.io/mbecker20/periphery:latest
    container_name: komodo-periphery
    restart: always
    user: "1000:1000"
    expose:
      - 8120
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/homelab/komodo/repos:/etc/komodo/repos:rw 
      - /mnt/homelab/komodo/stacks:/etc/komodo/stacks:rw 

  komodo-mongo:
    image: mongo
    container_name: komodo-mongo
    command: --quiet # suppress mongo logs a bit
    restart: always
    user: "1000:1000"
    networks:
      - internal
    expose:
      - 27017
    volumes:
      - /mnt/homelab/komodo/data:/data/db:rw
      - /mnt/homelab/komodo/config:/data/configdb:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    user: "1000:1000"
    tty: true
    stdin_open: true
    networks:
      - web
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    volumes:
      - /mnt/homelab/minecraft:/data

  ollama:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: ollama
    restart: always
    networks:
      - web
    expose:
      - 8080 # ui
      - 11434 # api
    volumes:
      - /mnt/homelab/ollama:/root/.ollama:rw
      - ollama-open-webui:/app/backend/data:rw
    security_opt:
      - label=type:nvidia_container_t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    user: "1000:1000"
    networks:
      - web
    expose:
      - 8096
    volumes:
      - jellyfin-config:/config:rw
      - jellyfin-cache:/cache:rw
      - /mnt/media:/data/media/:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    security_opt:
      - label=type:nvidia_container_t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    restart: always
    networks:
      - web
    volumes:
      - /mnt/media:/data:rw
    environment:
      - OPENVPN_OPTS=--pull-filter ignore ifconfig-ipv6
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - CREATE_TUN_DEVICE=true
    security_opt:
      - label=disable
    cap_add:
      - NET_ADMIN
      - MKNOD
    expose:
      - 9091 # transmission
      # any services proxied through this container need to declare ports here
      - 9696 # prowlarr
      - 8989 # sonarr
      - 8787 # readarr
      - 8686 # lidarr
      - 7878 # radarr
    devices:
      - /dev/net/tun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    user: 1000:1000 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/homelab/prowlarr:/config:rw
    network_mode: "service:transmission-openvpn"
    depends_on:
      - transmission-openvpn 
    restart: always

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    user: 1000:1000 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/homelab/lidarr:/config:rw
      - /mnt/media:/data:rw
    network_mode: "service:transmission-openvpn"
    depends_on:
      - transmission-openvpn 
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    user: 1000:1000 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/homelab/sonarr:/config:rw
      - /mnt/media:/data:rw
    network_mode: "service:transmission-openvpn"
    depends_on:
      - transmission-openvpn 
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    user: 1000:1000 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/homelab/radarr:/config:rw
      - /mnt/media:/data:rw
    network_mode: "service:transmission-openvpn"
    depends_on:
      - transmission-openvpn 
    restart: always

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    user: 1000:1000 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/homelab/readarr:/config:rw
      - /mnt/media:/data:rw
    network_mode: "service:transmission-openvpn"
    depends_on:
      - transmission-openvpn 
    restart: always

  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: yt-dlp-webui
    networks:
      - web
    expose:
      - 3033
    volumes:
      - /mnt/media/yt-dlp:/downloads:rw
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: always

  rathole:
    image: rapiz1/rathole
    container_name: rathole
    restart: always
    network_mode: host
    volumes:
      - /home/core/compose-files/docker/rathole/rathole.toml:/app/config.toml:ro
    command: --client /app/config.toml

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    environment:
      - CF_API_KEY=${CF_API_KEY}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - DNS=${DNS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/core/acme/:/etc/traefik/acme:rw
      - /home/core/compose-files/docker/traefik/static.toml:/etc/traefik/traefik.toml:ro
      - /home/core/compose-files/docker/traefik/dynamic.toml:/etc/traefik/dynamic.toml:ro
      - /home/core/compose-files/docker/traefik/captcha.html:/captcha.html:ro
      - logs:/var/log/traefik
    networks:
      - web
      - dns
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
    expose:
      - "8080:8080"
    depends_on:
      - crowdsec
      - loki

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.1-2
    container_name: crowdsec
    restart: always
    networks:
      - web
    expose:
      - 8080
      - 7422 
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK: ${TRAEFIK_BOUNCER_KEY}
    volumes:
      - /home/core/compose-files/docker/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - /home/core/compose-files/docker/crowdsec/profiles_captcha_only.yaml:/etc/crowdsec/profiles.yaml:ro
      - logs:/var/log/traefik:ro
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    depends_on:
      - loki

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    # user: "1000:1000"
    networks:
      dns: 
        ipv4_address: 172.55.0.10 
    volumes:
      - /mnt/homelab/adgaurd:/opt/adguardhome/conf:rw
      - adguard-work:/opt/adguardhome/work:Z
      - /mnt/homelab/letsencrypt:/opt/adguardhome/certs/:ro
    expose:
      - 80 # webui
      - 53 # dns - not used
      - 853 # dot
      - 443 # doh

  lego:
    image: goacme/lego
    container_name: lego-certbot
    restart: always
    user: "1000:1000"
    environment:
      - CLOUDFLARE_EMAIL=${CF_API_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_API_KEY}
    command:
      --accept-tos
      --email ${CF_API_EMAIL} --dns cloudflare 
      --domains dns.${DOMAIN} --path /etc/letsencrypt/ 
      run
    volumes:
      - /mnt/homelab/letsencrypt:/etc/letsencrypt:rw

  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    user: "1000:1000"
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET}
    networks:
      - web
    expose:
      - 8080
    volumes:
      - /home/core/compose-files/docker/searxng:/etc/searxng:rw

  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    restart: always
    networks:
      - web
    expose:
      - 80

  languagetool:
    image: meyay/languagetool
    container_name: languagetool
    restart: always
    user: "1000:1000"
    networks:
      - web
    expose:
      - 8010
    environment:
      download_ngrams_for_langs: en
      langtool_languageModel: /ngrams
      langtool_fasttextModel: /fasttext/lid.176.bin
    volumes:
      - /mnt/homelab/languagetool/ngrams:/ngrams:rw
      - /mnt/homelab/languagetool/fasttext:/fasttext:rw

  # configures a gh action runner to redeploy this file
  homelab-github-runner:
    image: myoung34/github-runner:debian-bookworm
    container_name: homelab-github-runner  
    network_mode: host # allows containers to use tailscale dns
    environment:
      ORG_NAME: LegitCamper
      REPO_URL: https://github.com/LegitCamper/homelab
      ACCESS_TOKEN: ${SELF_HOSTED_RUNNER}
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_POLL_INTERVAL: 604800 # every 7 days
    restart: always

  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    volumes:
      - /home/core/compose-files/docker/loki/:/mnt/config:ro
    command: -config.file=/mnt/config/config.yml
    networks:
      - internal
    expose:
     - 3100  
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail:3.3.2
    volumes:
      - /home/core/compose-files/docker/promtail:/mnt/config:ro
      - logs:/var/log:ro
    command: -config.file=/mnt/config/config.yml
    expose:
      - 9080
    networks:
      - internal
    depends_on:
      - loki
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise 
    user: "1000:1000"
    expose:
      - 3000
    networks:
      - internal
      - web
    volumes:
      - /mnt/homelab/grafana_data:/var/lib/grafana:rw
      - /home/core/compose-files/docker/grafana/:/etc/grafana/provisioning/datasources:rw
    depends_on:
      - loki
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: "1000:1000"
    networks:
      - internal
    expose:
      - 9090
    restart: always
    volumes:
      - /home/core/compose-files/docker/prometheus:/etc/prometheus:ro
      - /mnt/homelab/prometheus:/prometheus:rw
    command:
      - --config.file=/etc/prometheus/config.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - node_exporter

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host -–collector.systemd -–collector.processes
    networks:
      - internal
    expose:
      - 9100
    restart: always
    volumes:
      - /:/host:ro,rslave

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:latest
    container_name: dcgm-exporter
    networks:
      - internal
    expose:
      - 9400
    restart: always
    security_opt:
      - label=type:nvidia_container_t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    restart: always
    expose:
      - 8080
    networks:
      - internal
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      - /dev/disk/:/dev/disk:ro 
    devices:
      - /dev/kmsg:/dev/kmsg

  portfolio:
    image: ghcr.io/legitcamper/portfolio-site:latest
    container_name: portfolio
    restart: always
    networks:
      - web
    expose:
        - 8000

  mom-contact:
    image: ghcr.io/legitcamper/mom-contact:latest
    container_name: mom-contact
    restart: always
    networks:
      - web
    expose:
        - 8000
