global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9090
- job_name: homelab_node_exporter
  static_configs:
    - targets:
      - node-exporter:9100
# - job_name: homelab_docker_engines
#   static_configs:
#     - targets:
#       - homelab:9323
# - job_name: homelab_docker_containers
#   static_configs:
#     - targets:
#       - homelab:3080
# - job_name: external_app
#   static_configs:
#     - targets:
#       - remote.server:3080
#       - remote.server:3081
