pageInfo:
  title: Sawyer's Homelab!
  description: Welcome to your new dashboard!
  footerText: Hello from the other side
  navLinks:
    - title: Homelab settings
      path: https://github.com/LegitCamper/homelab/dashy
appConfig:
  theme: dracula
  layout: auto
  iconSize: large
  language: en
  statusCheck: true
  webSearch:
    searchEngine: custom
    customSearchEngine: https://search.sawyer.services?q=
  disableConfiguration: false
sections:
  - name: Productivity
    displayData:
      collapsed: false
      cols: 1
      sortBy: most-used
      rows: 1
      hideForGuests: false
    items:
      - title: NextCloud
        description: Cloud office suit and collaboration platform
        icon: hl-nextcloud
        id: 0_1302_nextcloud
      - title: VS Code Web
        description: Cloud based VS Code development environment
        icon: hl-vscode
        id: 1_1302_vscodeweb
  - name: Networks - 2000's
    items:
      - title: Pi-Hole
        description: DNS settings for ad & tracker blocking
        icon: hl-pihole
        id: 0_1318_pihole
        url: http://127.0.0.1:2001/admin
        statusCheckUrl: http://pihole/admin
        statusCheckAllowInsecure: true
      - title: SmokePing
        description: Network latency monitoring
        icon: hl-smokeping
        id: 1_1318_smokeping
        url: ''
        statusCheckUrl: http://smokeping
      - title: LibreSpeed
        description: Local network speed and latency test
        icon: hl-librespeed
        id: 2_1318_librespeed
    widgets:
      - type: public-ip
        id: 0_1318_publicip
      - type: pi-hole-stats
        options:
          hostname: http://pihole
          apiKey: xxxxxxxxxxxxxxxxxxxxxxx
        id: 1_1318_piholestats
      - type: pi-hole-traffic
        options:
          hostname: http://pihole
          apiKey: xxxxxxxxxxxxxxxxxxxxxxx
        id: 2_1318_piholetraffic
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: System Maintence - 5000's
    items:
      - title: Portainer
        description: Docker container management
        icon: hl-portainer
        id: 0_2053_portainer
      - title: Prometheus
        description: System Statistics Aggregation with PromQL
        icon: hl-prometheus
        url: ''
        id: 1_2053_prometheus
      - title: Cockpit
        description: web-based graphical interface for servers
        icon: hl-cockpit
        id: 2_2053_cockpit
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Media
    items:
      - title: Plex
        description: Self-Hosted Media Streaming Service
        icon: hl-plex
        id: 0_480_plex
      - title: Tautulli
        description: Monitoring and statistics for Plex
        icon: hl-tautulli
        id: 1_480_tautulli
      - title: qBittorrent
        description: managing torrents
        icon: hl-qbittorrent
        id: 2_480_qbittorrent
      - title: Couch Potato
        description: Automatic Movie Downloading via NZBs & Torrents
        icon: hl-couchpotato
        id: 3_480_couchpotato
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: CVE's
    widgets:
      - type: cve-vulnerabilities
        options: null
        sortBy: publish-date
        productId: 28125
        hasExploit: false
        minScore: 5
        limit: 30k
        id: 0_376_cvevulnerabilities
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Daily
    widgets:
      - type: apod
        id: 0_2652_apod
      - type: xkcd-comic
        options: null
        comic: latest
        id: 0_1407_xkcdcomic
  - name: GitHub Trending
    widgets:
      - type: github-trending-repos
        options:
          limit: 8
          since: weekly
        id: 0_1438_githubtrendingrepos
    displayData:
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Server Stats
    displayData:
      collapsed: false
      cols: 2
    widgets:
      - type: gl-current-cpu
        options:
          hostname: http://127.0.0.1:5002
        id: 0_1190_glcurrentcpu
      - type: gl-cpu-history
        options:
          hostname: http://127.0.0.1:5002
          limit: 60
        id: 1_1190_glcpuhistory
      - type: gl-network-traffic
        options:
          hostname: http://127.0.0.1:5002
          limit: 500
        id: 2_1190_glnetworktraffic
      - type: gl-network-interfaces
        options:
          hostname: http://127.0.0.1:5002
        id: 3_1190_glnetworkinterfaces
      - type: gl-disk-space
        options:
          hostname: http://127.0.0.1:5002
        id: 4_1190_gldiskspace
      - type: gl-cpu-temp
        options:
          hostname: http://127.0.0.1:5002
        id: 5_1190_glcputemp
