[global]
checkNewVersion = true
sendAnonymousUsage = false

[logs]
[logs.general]
level = "INFO"
[logs.access]
enabled = true
format = "json"
[logs.access.fields]
[logs.access.fields.headers]
defaultMode = "keep"
[logs.access.fields.headers.names]
X-Forwarded-Tls-Client-Cert-Info = "keep"
X-Real-IP = "keep"

[accesslog]
filepath = "/var/log/traefik/access.log"

[api]
insecure = true
dashboard = true
debug = true
disableDashboardAd = true

[serversTransport]
insecureSkipVerify = true
[tcpServersTransport.tls]
insecureSkipVerify = true

[entryPoints]
[entryPoints.web]
address = ":80"
asDefault = false
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"
permanent = true

[entryPoints.websecure]
address = ":443"
asDefault = true
proxyProtocol.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]
forwardedHeaders.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]

[entryPoints.ssh]
address = ":22"
asDefault = false
proxyProtocol.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]
forwardedHeaders.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]

[entryPoints.dot]
address = ":853"
asDefault = false
proxyProtocol.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]
forwardedHeaders.trustedIPs = [
  "24.199.78.82",
  "172.16.0.0/16",
  "100.64.0.0/10",
  "127.0.0.1/32",
]

[providers.file]
directory = "/etc/traefik/"
watch = true
filename = "dynamic.toml"
debugLogGeneratedTemplate = true

[certificatesResolvers]
[certificatesResolvers.tailscale.tailscale]
[certificatesResolvers.cloudflare]
[certificatesResolvers.cloudflare.acme]
email = "email"
storage = "/etc/traefik/acme/acme.json"
[certificatesResolvers.cloudflare.acme.dnsChallenge]
provider = "cloudflare"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
[propogation]
disableCheck = true
[certificatesResolvers.cloudflare.acme.httpChallenge]
entryPoint = "web"
