[global]
checkNewVersion = true
sendAnonymousUsage = false

[log]
level = "INFO"

[accesslog]
filepath = "/var/log/traefik/access.log"

[api]
insecure = true
dashboard = true
debug = true
disableDashboardAd = true

[serversTransport]
insecureSkipVerify = true
[tcpServersTransport]
[tcpServersTransport.tls]
insecureSkipVerify = true

[entryPoints]
[entryPoints.web]
address = ":80"
reusePort = true
asDefault = false
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"
permanent = true

[entryPoints.websecure]
address = ":443"
reusePort = true
asDefault = true

[entryPoints.dot]
address = ":853"
reusePort = true
asDefault = false

[providers.file]
directory = "/etc/traefik/"
watch = true
filename = "dynamic.toml"
debugLogGeneratedTemplate = true

[certificatesResolvers]
[certificatesResolvers.cloudflare]
[certificatesResolvers.cloudflare.acme]
email = "email"
storage = "/etc/traefik/acme/acme.json"
[certificatesResolvers.cloudflare.acme.dnsChallenge]
provider = "cloudflare"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
[propogation]
disableCheck = true
[certificatesResolvers.cloudflare.acme.httpChallenge]
entryPoint = "web"
