name: Update Homelab Servers

on:
  push:
    branches:
      - main
      - overhaul
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v4

      - name: install ansible
        run: sudo apt-get install -y ansible

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          # known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run gateway playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: gateway.yml
          directory: ./
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          inventory: |
            [all]
            143.198.65.127
          configuration: |
            [defaults]
            host_key_checking = False
            [ssh_connections]
            pipelining = true
          options: |
            --inventory .hosts
            --verbose

      - name: Run homeserver playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: homeserver.yml
          directory: ./
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          inventory: |
            [all]
            homeserver
          configuration: |
            [defaults]
            host_key_checking = False
            [ssh_connections]
            pipelining = true
          options: |
            --inventory .hosts
            --verbose
