name: Update Homelab Servers

on:
  push:
    branches:
      - main
      - overhaul
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - uses: actions/checkout@v4

      - name: Run gateway playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: gateway.yml
          directory: ./
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          options: |
            --inventory gateway
            --verbose

      - name: Run homeserver playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: homeserver.yml
          directory: ./
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
          options: |
            --inventory homeserver
            --verbose
